name: Validation
on:
- push
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - run: go test .
  lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: golangci/golangci-lint-action@v3
